language: cpp

#env:
#  global:
#    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
#    - BOOST_VERSION=default
#    - BOOST_ROOT="${DEPS_DIR}/boost/installed/boost_1_60_0"
#    - LD_LIBRARY_PATH="${BOOST_ROOT}/lib":${LD_LIBRARY_PATH}
    
sudo: required #false
    
branches:
  only:
    - master
  except:
    - gh-pages
    
# Install dependencies
#addons:
#  apt:
#    packages:
#      - doxygen
#      - doxygen-doc
#      - doxygen-latex
#      - doxygen-gui
#      - graphviz
    
matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install python-software-properties 
        - sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2
        - sudo apt-get update
        - sudo apt-get install doxygen
        - sudo apt-get install graphviz
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: 
        - COMPILER=g++-5
        - BOOST_VERSION="1.60.0"
        - GH_REPO_NAME: NetworkTest
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
        - GH_REPO_REF: github.com/rokoDev/NetworkTest.git
    - os: osx
      compiler: clang
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - COMPILER=clang++
        - BOOST_VERSION="1.60.0"
  
#before_install: ./scripts/before_install.sh

install: 
  - ./scripts/before_install.sh
  #- export CMAKE_OPTIONS=${CMAKE_OPTIONS}" -DBOOST_ROOT=${DEPS_DIR}/boost/installed/boost_1_60_0"

script: 
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" -DBOOST_ROOT=${DEPS_DIR}/boost/installed/boost_1_60_0 -D CMAKE_CXX_COMPILER=${COMPILER}"
  - ./scripts/build_test_install.sh
  
# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

notifications:
  recipients:
    - rokodevnet@gmail.com
  email:
    on_success: change
    on_failure: always
    