branches:
  only:
    - master

language: cpp
  
os:
- osx

osx_image:
- beta-xcode6.1
- xcode8

compiler:
- clang
- gcc
  
branches:
  only:
  - master
  
before_install: ./scripts/before_install.sh

addons:
  apt:
    sources:
    - boost-latest

#install:

script: ./scripts/build_test_install.sh

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    