branches:
  only:
    - master

language: cpp
compiler:
  - clang
  - gcc

install:
if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
  CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz"
  mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}
else
  brew install cmake
fi
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev

script:
- mkdir build
- cd build
- cmake -DBOOST_ROOT=$boost_installation_prefix ..
- cmake --build .
- cd tests
- ctests -VV

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    