branches:
  only:
    - master

language: cpp
  
os:
- osx

compiler:
  - clang
  - gcc
  
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
      brew upgrade cmake 3.6.1;
    fi;

addons:
  apt:
    sources:
        - boost-latest

install:
- cmake --version
- if [ $TRAVIS_OS_NAME = osx ]; then
       brew outdated boost || brew upgrade boost;
    fi;
#  - sudo apt-get update -qq
#  - sudo apt-get install libboost-test-dev

script:
- mkdir build
- cd build
- cmake -DBOOST_ROOT=$boost_installation_prefix ..
- cmake --build .
- cd tests
- ctest -VV

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    