language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - BOOST_VERSION=default
    - BOOST_ROOT=${DEPS_DIR}/boost
    
sudo: required
    
branches:
  only:
    - master
  
matrix:
  include:
     - os: linux
       dist: trusty
       compiler: gcc
       sudo: required
       addons:
         apt:
           sources: 
             - ['ubuntu-toolchain-r-test']
             #- boost-latest
             #- george-edison55-precise-backports
           packages: 
             #- ['g++-4.7']
             - g++-4.8
             #- libboost-test1.60-dev
             #- libboost-test1.60.0
             #- cmake
             #- cmake-data
       env:
         - BOOST_VERSION="1.60.0" # Boost 1.61
         #- BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz"
#    - os: osx
#      osx_image: beta-xcode6.1
#      compiler: clang
#    - os: osx
#      osx_image: xcode8
#      compiler: clang
#    - os: osx
#      osx_image: beta-xcode6.1
#      compiler: gcc
#    - os: osx
#      osx_image: xcode8
#      compiler: gcc
  
#before_install: ./scripts/before_install.sh

install: ./scripts/before_install.sh

script: ./scripts/build_test_install.sh

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    