language: cpp

env:
  global:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - BOOST_VERSION=default
    - BOOST_ROOT="${DEPS_DIR}/boost/installed/boost_1_60_0"
    
sudo: required
    
branches:
  only:
    - master
  
matrix:
  include:
     - os: linux
       dist: trusty
       compiler: gcc
       sudo: required
       addons:
         apt:
           sources: 
             - ['ubuntu-toolchain-r-test']
           packages:
             - g++-4.9
       env:
         - BOOST_VERSION="1.60.0"
  
#before_install: ./scripts/before_install.sh

install: 
  - ./scripts/before_install.sh
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" -DBOOST_ROOT=${DEPS_DIR}/boost/installed/boost_1_60_0"

script: ./scripts/build_test_install.sh

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    