branches:
  only:
    - master

language: cpp
  
matrix:
  include:
    - os: osx
      osx_image: beta-xcode6.1
      compiler: clang
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.1
      compiler: gcc
    - os: osx
      osx_image: xcode8
      compiler: gcc
#os:
#- osx
#
#osx_image:
#- beta-xcode6.1
#- xcode8

#compiler:
#- clang
#- gcc
  
branches:
  only:
  - master
  
before_install: ./scripts/before_install.sh

addons:
  apt:
    sources:
    - boost-latest

#install:

script: ./scripts/build_test_install.sh

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    