branches:
  only:
    - master

language: cpp
compiler:
  - clang
  - gcc
  
os:
- osx

addons:
  apt:
    sources:
        - boost-latest

install:
- cmake --version
#  - sudo apt-get update -qq
#  - sudo apt-get install libboost-test-dev

script:
- mkdir build
- cd build
- cmake -DBOOST_ROOT=$boost_installation_prefix ..
- cmake --build .
- cd tests
- ctests -VV

notifications:
  recipients:
    - mishaDoter@gmail.com
  email:
    on_success: change
    on_failure: always
    