version: 1.0.{build}
os: Visual Studio 2015

branches:
  only:
    - master
    
platform:
  #- x86
  - x64
configuration:
  - Release
  
matrix:
  fast_finish: true
  
build:
  verbosity: detailed
  
before_build:
  - cmake -E make_directory build
  - cd build
  #- cmake -G "MinGW Makefiles" "-DBUILD_SHARED_LIBS=YES" .. #"Visual Studio 14 2015 Win64" "-DBUILD_SHARED_LIBS=YES" ..
  - cmake -G "Visual Studio 14 2015 Win64" "-DBUILD_SHARED_LIBS=YES" ..

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

build_script:
  #- rmdir /Q /S build installed deps
  #- md build
#  - cmake -E make_directory build
#  - cd build
  #- cmake -DCMAKE_BUILD_TYPE=Release .. #-G "Visual Studio 14 2015 Win64" ..
#  - cmake -G "Visual Studio 14 2015 Win64" ..
#  - cmake --build . --config Release
  - cmake --build . --config %CONFIGURATION%
  #- ctest
  
test_script:
  - cd tests
  - cmd: ctest -C %CONFIGURATION% -VV
  #- ctest -VV -C Release --timeout 600
  #- cd tests
#  - ctest -C Debug -VV