version: 1.0.{build}
os: Visual Studio 2015

branches:
  only:
    - master
    
platform:
  - x64
  
configuration:
  - Release
  
matrix:
  fast_finish: true
  
build:
  verbosity: detailed

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

build_script:
  - cmake -E make_directory build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config %CONFIGURATION%
  
test_script:
  - cd tests/%CONFIGURATION%
  - cmd: dir
  - cmd: ctest -C %CONFIGURATION% -VV
  #- ctest -VV -C Release --timeout 600
  #- cd tests
#  - ctest -C Debug -VV