version: 1.0.{build}
os: Visual Studio 2015

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master
    
platform:
  - x64
  
configuration:
  - Release
  
matrix:
  fast_finish: true
  
build:
  verbosity: detailed

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
  PATH: "$($env:PATH);$env:BOOST_LIBRARYDIR"

build_script:
  - cmake -E make_directory build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_TESTS=ON ..
  - cmake --build . --config %CONFIGURATION%
  
  #- cd tests/%CONFIGURATION%
  - cmd: 'cd C:\projects\networktest\build\tests\Release'
  - cmd: dir
  #- ctest -C %CONFIGURATION% #--build-exe-dir %CONFIGURATION%
  #- make test
  - cmd: test_executable.exe
  #- cmd: ctest -VV -C %CONFIGURATION% --timeout 600
  
#test_script:
#  - cd tests/%CONFIGURATION%
#  - cmd: dir
#  #- cmd: ctest -C %CONFIGURATION% -VV
#  #- ctest -VV -C Release --timeout 600
#  #- cd tests
##  - ctest -C Debug -VV
#  - ctest -VV

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))