version: 1.0.{build}
os: Visual Studio 2015

#init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master
    
platform:
  - x64
  
configuration:
  - Release
  
matrix:
  fast_finish: true
  
build:
  verbosity: detailed

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

build_script:
  - cmake -E make_directory build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config %CONFIGURATION%
  
test_script:
  - cmd: set PATH=%PATH%;%BOOST_LIBRARYDIR%
  - cmd: 'cd C:\projects\networktest\build\tests\%CONFIGURATION%'
  #- cmd: dir
  - cmd: test_executable.exe --log_level=test_suite #--run_test=int_test,config_test
#  #- cmd: ctest -C %CONFIGURATION% -VV
#  #- ctest -VV -C Release --timeout 600
#  #- cd tests
##  - ctest -C Debug -VV
#  - ctest -VV

#on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
  - provider: Email
    to:
      - rokodevnet@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_success: true #|false
    on_build_failure: true #|false
    on_build_status_changed: true #|false