os: Visual Studio 2015

branches:
  only:
    - master
    
platform: x64
configuration:
  - Release
  
build:
  verbosity: detailed

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

build_script:
  #- rmdir /Q /S build installed deps
  #- md build
  - cmake -E make_directory build
  - cd build
  #- cmake -DCMAKE_BUILD_TYPE=Release .. #-G "Visual Studio 14 2015 Win64" ..
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  #- ctest
  
test_script:
  - cd tests
  #- cmd: ctest -C Release -VV
  - ctest -VV -C Release
  #- cd tests
#  - ctest -C Debug -VV